### ISSUE TITLE
Issue importing your module

### ISSUE THREAD

**Issue by Vytek** [KingAkeem/go-dms#1]
If I try to import your module:

go: radar2tacview imports
        github.com/KingAkeem/go-dms/dms: github.com/KingAkeem/go-dms@v0.0.0-20230917152744-2873de0acbee: parsing go.mod:
        module declares its path as: go-dms
                but was required as: github.com/KingAkeem/go-dms

I think that the problem is the go.mod:

module go-dms

would be:

module github.com/KingAkeem/go-dms

**Comment by KingAkeem** [comment]
The `go.mod` was recently added so I likely missed a change within the README. Feel free to submit a pull request to update the documentation. The library isn't actively used since it's just an example of using WASM.

**Comment by Vytek** [comment]
I think it is necessary to regenerate the mod file using: go mod init https://github.com/KingAkeem/go-dms
From what I see, even if I forked the code my go mod should be go mod init https://github.com/vytek/go-dms If in fact you search among the Packages on Golang you don't find: https://pkg.go. dev/search?q=go-dms Unless the repo is no longer of interest to you and a hardfork needs to be done (which I don't think is interesting to you..) Tell me how to proceed and if you can recreate the go file correctly. mods etc..

**Comment by KingAkeem** [comment]
The repo isn't really of interest to me, I hadn't worked on it in a few years and just noticed there was a new fork so I decided to mess around with it. It wasn't intended to be used by others. But if I have time this weekend, then I can take a look at it. Otherwise, feel free to do whatever you'd like to resolve the issue on your side. It's GNU GPL v3.0 so you can modify it as you'd like.

**Comment by KingAkeem** [comment]
I've made some updates including replacing the `module` path with `go.mod`. This may have resolved your issue, but I'm not sure so you can try it out and let me know.

**Comment by Vytek** [comment]
All ok: https://pkg.go.dev/github.com/KingAkeem/go-dms#section-readme Thank you!

**Comment by KingAkeem** [comment]
Great and you're welcome, thank you for pointing it out.
